version: "3"

services:
  # Nombre contenedor
  app:
    build: .
    # Variables de entorno
    environment:
      MONGO_URL: "mongodb://db:27017/test"
    # Indica que debe iniciarse despues del contenedor "db"
    depends_on:
      - db
    ports:
      #Especifica el rango de puertos que se van a crear
      - "3000-3010:3000"
    volumes:
      - .:/usr/src
      - /usr/src/node_modules

  # Nombre contenedor
  db:
    image: mongo